/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as socalSol from "./Socal.sol";
export * as helper from "./helper";
export * as interface from "./interface";
export { Greeter__factory } from "./Greeter__factory";
